name: qlctfe
description: "Personal Finance Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.1.2

  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.2
  intl: ^0.20.2

  pie_chart: ^5.4.0
  fl_chart: ^0.68.0

  http: ^1.5.0
  dio: ^5.0.0

  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4

  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  permission_handler: ^11.0.1

  excel: ^4.0.2
  path_provider: ^2.1.3
  open_filex: ^4.3.2
  share_plus: ^10.0.2
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  file_saver: ^0.2.12

  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/piggy.png
    - assets/icons/expenses/
    - assets/icons/incomes/
    - assets/lang/en-US.json
    - assets/lang/vi-VN.json
